file_save_format = {
    'raw': 'fif',
    'bem': 'fif',
    'src': 'fif',
    'trans': 'fif',
    'fwd': 'fif',
    'eve': 'fif',
    'epo': 'fif',
    'cov': 'fif',
    'ave': 'fif',
    'inv': 'fif',
    'stc': 'pkl',
    'coords': 'pkl',
    'resec': 'nii',
    'resec_mni': 'pkl',
    'resec_txt': 'txt',
    'feat': 'pkl',
    'nodes': 'pkl',
    'dataset': 'pkl'
}

file_search_regexps = {
    'raw': r'.*raw.*\.fif',
    'bem': r'.*bem.*\.fif',
    'src': [r'.*src.*\.fif', r'.*source_space.*\.fif', r'.*source-space.*\.fif'],
    'trans': r'.*trans.*\.fif',
    'fwd': [r'.*fwd.*\.fif', r'.*forward.*\.fif'],
    'eve': r'.*eve.*',
    'epo': r'.*epo.*',
    'cov': r'.*cov.*\.fif',
    'ave': [r'.*ave.*\.fif', r'.*evoked.*\.fif'],
    'inv': r'.*inv.*\.fif',
    'stc': [r'.*stc.*\.fif', r'.*stc.*\.pkl'],
    'coords': [r'.*coord.*\.pkl', r'.*coordinate.*\.pkl'],
    'resec': r'.*resec.*\.nii.*',
    'resec_mni': r'.*resec.*\.pkl.*',
    'resec_txt': r'.*resec.*\.txt.*',
    'feat': r'.*feat.*\.pkl.*',
    'nodes': r'.*nodes.*\.pkl.*',
    'dataset': r'.*dataset.*\.pkl.*'
}

tree_data_types = (
    'raw',
    'bem',
    'src',
    'trans',
    'fwd',
    'eve',
    'epo',
    'cov',
    'ave',
    'inv',
    'stc',
    'coords',
    'resec',
    'resec_txt',
    'resec_mni',
    'feat',
    'nodes',
    'dataset'
)

subject_data_types = (
    'raw',
    'raw_fp',
    'bem',
    'src',
    'trans',
    'fwd',
    'eve',
    'epo',
    'cov',
    'ave',
    'inv',
    'stc',
    'resec',
    'resec_txt',
    'resec_mni',
    'coords',
    'feat',
    'nodes',
    'dataset'
)